### PR TITLE
Build APK on push with Github actions

### PR DESCRIPTION
**Pull request by MrRar**
If the following actions secrets are present in the repo then a signed APK will be created:
SIGNING_KEY_ALIAS
SIGNING_KEY_PASSWORD
SIGNING_STORE_PASSWORD
NIGHTLY_STORE_FILE

NIGHTLY_STORE_FILE is a base64 encoded .jks file.
You can generate it by running: `openssl base64 < your_signing_keystore.jks | tr -d '\n' | tee your_signing_keystore_base64_encoded.txt`

Other secrets are self explanatory I think.

If no secrets are present, an unsigned APK is generated.

I added some gradle related files to the repo to get it working. This seems to be the norm. See: https://stackoverflow.com/questions/21762180/should-you-include-or-ignore-gradle-wrapper-properties

Fixes: https://github.com/flavio20002/CatholicBible/issues/2

### CODE REVIEW

**Comment by flavio20002** [comment]
Wonderful, thanks a lot. I will try a build soon and push on Play Store on
Beta.


Il ven 28 apr 2023, 19:43 Johannes Fritz ***@***.***> ha
scritto:

**Comment by flavio20002** [comment]
Fixed with https://github.com/flavio20002/CatholicBible/commit/2ec993381f9f6ed0adbbe9acd4851b99f137d6d4

**Comment by MrRar** [comment]
> Fixed with [2ec9933](https://github.com/flavio20002/CatholicBible/commit/2ec993381f9f6ed0adbbe9acd4851b99f137d6d4)

Was it not working for you? I agree that does simplify the code a little bit by echoing the Github secret directly instead of putting it in an environment variable first. But if you do that make sure to remove the environment variable https://github.com/flavio20002/CatholicBible/blob/2ec993381f9f6ed0adbbe9acd4851b99f137d6d4/.github/workflows/build-apk.yml#L27
Because that's now useless.

**Comment by flavio20002** [comment]
@MrRar Yes, also the signing of the apk is not needed, because apk is used only for fast tests. The aab is instead published on play store.

**Pull request merged**
